// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactionsService.Models;

namespace ReactionsService.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactionsService.Models.Reaction", b =>
                {
                    b.Property<Guid>("ReactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfReactionID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReactionID");

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            ReactionID = new Guid("8ca02e0f-a565-43d7-b8d1-da0a073118fb"),
                            PostID = 1,
                            TypeOfReactionID = 1,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("ReactionsService.Models.TypeOfReaction", b =>
                {
                    b.Property<int>("TypeOfReactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeOfReactionID");

                    b.ToTable("TypeOfReaction");
                });
#pragma warning restore 612, 618
        }
    }
}
